### PR TITLE
feat: Removes JKT public headers for compatibility with compact

### PR DESCRIPTION
**Pull request by EthanHeilman**
This PR looks at removing the JTK public header. We haven't reached a conclusion if we want to do this or not, but I wanted to candidate PR to see what this change would look like.

Additionally this PR
* Fixes typo where JKT is written JTK.
* Fixes https://github.com/openpubkey/openpubkey/issues/137 by removing JKT public header outside of GQ Tokens

## Tests

- [X] Manual Github Actions test https://github.com/openpubkey/gha-test/actions/runs/8789750568/job/24120196588
- [X] Manual Gitlab test https://gitlab.com/openpubkey/gl-test/-/pipelines/1263400903
- [X] MFA Cosigner test fc7fd6c4d21d508569c02eff3fa5795abe19f671

### CODE REVIEW

**Comment by EthanHeilman** [comment]
@jonnystoten Any reason not to do this?

**Review by mrjoelkamp — APPROVED** [review]
lgtm

**Review by jonnystoten — COMMENTED** [review]
The code looks good to me, however I'm not sure I understand how this fixes #137, do you mean it just makes it no longer relevant? Apologies if I'm misunderstanding something there!

**Comment by EthanHeilman** [comment]
> The code looks good to me, however I'm not sure I understand how this fixes #137, do you mean it just makes it no longer relevant?

You have the right of it. 137 isn't needed if this is merged.

**Pull request merged**
